{% set name = "flake8-comprehensions" %}
{% set version = "2.1.0" %}
{% set sha256 = "f0b61d983d608790abf3664830d68efd3412265c2d10f6a4ba1a353274dbeb64" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools
  run:
    - python >=3.4
    - flake8 !=3.2.0

test:
  commands:
    - "flake8 --version | grep flake8-comprehensions:"

about:
  home: https://github.com/adamchainz/flake8-comprehensions
  license: ISC
  license_file: LICENSE
  summary: 'A flake8 plugin that helps you write better list/set/dict comprehensions.'
  dev_url: https://github.com/adamchainz/flake8-comprehensions

extra:
  recipe-maintainers:
    - dopplershift
