{% set name = "flake8-comprehensions" %}
{% set version = "3.10.1" %}
{% set sha256 = "412052ac4a947f36b891143430fef4859705af11b2572fbb689f90d372cf26ab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - flake8 >=3.0,!=3.2.0
    - importlib_metadata

test:
  commands:
    - 'flake8 --version | grep flake8-comprehensions:'

about:
  home: https://github.com/adamchainz/flake8-comprehensions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin that helps you write better list/set/dict comprehensions.
  dev_url: https://github.com/adamchainz/flake8-comprehensions

extra:
  recipe-maintainers:
    - dopplershift
