travis:
  secure:
    BINSTAR_TOKEN: rhWMkh35KDJsy4wfP2LlPquJ+rpD7Ej1lm3LP7gDedstEfAUboa1I6YRlJnruMCWx90sl4ap+GgLqmL4pamt+lMSwPeVkfGJmbT9ykHBUFVkYCGCT6a/cA/kkBqczaa8O3wqh/tPv07UJvLL7+ghz3o54Z4YAhnWUyLwa26VioQvO4iqA9ZHk54yy18pS9M/aOB0iTchPLyyfH0YyE/JwAxi36qPrdv7zxiv7q5IlL3b466yrQa8xzNbcTrl9rwBeWMyawhZVSOWwebqreFnFaq4ZkjMjyzmu8VvK+AitqcOqsxZWeT5b3RPi+8hzow6p6jPucP+4HMOtg3nju6GDRoIrvojPMBidpcTQoOiJKFB2bMP40upOkldmRe1CFqvKHebdGXMXRbtGfVmVBnIpHmR0Fd1FeliHYg7H94VzCXh4vknIfrbGvXBqnwLDrWXphy0NTfsq9Neh2kG6mFovvcDSYA4KvkS0fTKaH81wgPZS3kEKm3tofjUaYjBF2Woov0JRdqPbucIf3qZCbY2MUz9ygo27qVBESIudmoW/TmmmLB/afjQo0bymQUf9iw7UmWHhowdJ+RKXIgVN46IQphEYS/AK2TkdG0d5YwG/rVzM9LOM6UozdVN0fYg/kZ8DscUpAfyCfmH3RLdwT3pKDmRrJGu7bmS600Q0uhs3TQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
