travis:
  secure:
    BINSTAR_TOKEN: HeAO+JWO0qA45bBQqZhfgglXjq1QOtd2w+OCIyj+RSFYe1KXCFTHJ1u6uUba5z8dRQx/4gjcdtVebLrBXJ76GtDNdmWGTgEE6d9zuAVSAhAw9bUypHRHqmotw8PrV3PRsTAy5zdXQqwvgJqPqO6TH06Sm8WJqkDM2Z32PJbgpdv6zb+oVQNykESYKDcVfAeH7Lrsn+gZeYdW78vwg0oJaQZ1dgX/yXvveO+3wKkwJWibWMQKj/n3FLgG+e2+mQVFGrhJ3rYWBKPdchlPEt4rBYEZz9hOwhHXu4ALs6qMPHCop0dLt0DSdgKODMJB6dps4yVi5soQ7dehR/YpQISPx0bVhW0YSzYI0SlZOcGlL/a64HxN5I+vZxzCDXBbcr9IBlJHq+nFgTXeTIsU6ehOVEAdGHFMu43TzBUNW9SkvmKM/KAcZhbhhHFtm96ka9OpmLwgVCtk+7HMzWwthB24ZXIT5WIe751DGYKtGNIcwFfKwvSwfqg+LlBhEui4XSGjRsyJb991To2C3BkWNAb9KxZYZOuc1WEOO+Ll65jwt0EnaG7sqoWn/F5UOX5ewvir7GnmDFjvVAMThGpw+fXZIgC/HCzkuIb2rqlkEFIbMSRx6xhf6IUA/bluwlBs09K5wNMfXYPO/LVKEeAWyL0Bc9Mwv2sK4hSIDhOs9iVoqZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
