travis:
  secure:
    BINSTAR_TOKEN: ZuUNUxhZo4j98dDBKRz8wCyFTqdpybfBN/3rAJ5jvmKFvLl+sO4CU9TSWMDF4AcHi3W3sNr2iYpQiBj5EnWM3Ips3RpIq2mL32CGgzYa5FBtP3lj64szpq2l8bQYaNlG/xGvPemQsbQXfiP020TX/UWxKgouLDM4ip6iQQ+TiYE5Bb4PTr9ozJ6wVd6Hye3e4jbzSvm0svPKAoBZ2zdaUgBeQIS/+pRy29GA47yW8sSP26k+ICU40k31ij4TyuRygcUhh4kX37iHV283tetNyPSW3T8WOPsftg3PdxVgo+KlcDHWfGtCzN59GhD0eYjftzwndMPJlnkKAMRz9kQ7gajDJEWvRuhXjSUauqLb5YPb7J4yPw2+QBCYNZpq5b/gCaMf9zlvxi+8vQuCkiLDGngjZfyr6W9Y0RlvnMI4I0uWcI39hust57Kz8XEL/1qoVPV2NV6NoXaetzic+qKOE9re0xcexQzmRjFhYym4/EHge//iTQDyVMk4wlPA7/1YJEXkSb8KXZ7vC5X3vJBA5rIT9KWrC1nTbEVPItTjNibj1N9ZM6ta1G3e2cZnKaCO24oednjqSLN6sLpLUeYq/c2bgak8FpURq6MRodxAffkpt7BK4C5ep86RYp8QsB8OIvDrfYaeqV0Tcah36EMWbyNwKNeY48ZtU1XTr5RSsRs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
