travis:
  secure:
    BINSTAR_TOKEN: uBtLFZ9BxWGBXo1y5bJy2Jzthcrukyfx1/2bExGUcAGMsFBEE32Ges7p028QNVrU5Ct9TbvzRGiGCwTzybnL3CgeVz1tJV/QCq37UpgdoPJaVC83L9GF+pokrH4OdEW9+Z6LEPrDUlrdHXj6lxt3c/fXDaLVAYTjF0NyLlN4FiNRPnghlUVEu6cZEQs+l67GgJhwyCjc/7HohWnbs59La2VfMpnk/DAJoTZeRqR+h/+yGwljy4ujakgofvuBxZDfhIOw0959Dxz2y3gRwc+Ejij3BSkZu/8IPzm2fI9s0CEpMhD6nNxBPmKUfy0PhZM+EolswnqouvcAxs14J+G+X0aUS+EyAQo7TrEEWuYbemSX6sVv2MgjfJXGD+YqHgq7vLpDcCBoX9EyeJ6ZG9g3nP0YoHUUmNumxOH7Jwd7IZ/cpqY5JMvMI+mkEzgYBN1wZ9KXhgY4fkCjHHu+4mgddCalT/MAzdm95WKT2trw9ZpQ1oiUQ99D+TrnNFNeZvnreZohbWoSjHDmKedEylBmO9vZ1bCMz143TwCKseR5lOotpT4g815aSJe6MCCf+J3sSOfmScQFKeeGCSsK+es4uyEJqqj1lXe/aguspcqhK32yPY3YVcvE8G3A7KEQXDfV1ZISF+cDY12Axp++Q210LGNYRym9yAbfn13GXOvXLC8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
